server:
  port: 8887
spring:
  thymeleaf:
    prefix:
      classpath: /templates/
    suffix: .html
    cache: false # 开发时关闭缓存,不然没法看到实时页面
  datasource:
    url: jdbc:h2:~/community
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
  devtools:
    restart:
      exclude: static/**,public/**

github:
  client:
    id: f54ac00d923aecf7eb34
    secret: ca752378e745f7c4f6422b1d431536971ea7fb91
  redirect:
    uri: http://localhost:8887/callback

#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
